version: '3.3'

services:
   db:
     image: mysql:5.7
     volumes:
       - db_data:/var/lib/mysql
       - ./wordpress.sql:/docker-entrypoint-initdb.d/init.sql
     restart: always
     ports:
       - "3306:3306"
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   composer:
     image: composer:latest
     volumes:
      - ./:/app
     command: install
     restart: 'no'

   wordpress:
     depends_on:
       - db
       - composer
     image: wordpress:latest
     hostname: wordpress
     ports:
       - "8000:80"
     restart: always
     working_dir: /var/www/html
     volumes:
      - ./:/var/www/html/wp-content
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress
       WORDPRESS_TABLE_PREFIX: wp_zbfwfemqwc_
       WORDPRESS_DEBUG: 1
       WORDPRESS_CONFIG_EXTRA: |
          define('WP_CACHE', false);
          define('WP_SITEURL', 'http://' . $$_SERVER['HTTP_HOST'] . '/');
          define('WP_HOME', 'http://' . $$_SERVER['HTTP_HOST'] . '/');

volumes:
    db_data: {}
